Shopify/pitchfork

ext/pitchfork_http/epollexclusive.h

Inspired by: https://yhbt.net/unicorn-public/20230301231205.M669849@dcvr/#R
It was introduced in Ruby 1.9 https://github.com/ruby/ruby/commit/8489ac41cadc1ef80ea57799bc833a831d1afdc6
> Allocates a  memory region, possibly  on stack.   If the given  size exceeds
> #RUBY_ALLOCV_LIMIT, it allocates a dedicated  opaque ruby object instead and
> let our GC sweep that region after use.  Either way you can fire-and-forget.
Currently RUBY_ALLOCV_LIMIT is defined as 1kB, `struct epoll_event` seem to be 12B on x86_64, so we'd only allocate if we need over 85 readers, which seem improbable.

Leverage Ruby's ALLOCV to save allocating in get_readers

---

CHANGELOG.md
docs/CONFIGURATION.md
docs/DESIGN.md
docs/FORK_SAFETY.md
examples/pitchfork.conf.rb
lib/pitchfork/configurator.rb
lib/pitchfork/http_server.rb
lib/pitchfork/worker.rb
test/integration/t0020-at_exit-handler.sh
test/integration/t0116-client_body_buffer_size.sh
test/integration/test_boot.rb
test/integration/test_reap_logging.rb
test/integration/test_reforking.rb
test/slow/test_signals.rb
test/unit/test_configurator.rb

Now that the mold is forked rather than promoted, it makes more sense.

Rename `after_promotion` in `after_mold_fork` and `after_fork` in `after_worker_fork`

---

docs/REFORKING.md
lib/pitchfork/http_server.rb

Ensure a better alignment in `ps` output, which makes it easier to understand the cluster state at a glance.

Make proc titles more readable

---

CHANGELOG.md
lib/pitchfork.rb

It has several advantages, first we only need to copy fiber locals, actual thread local variables are preserved.
Additionally any code using `Thread.current` as a hash key won't be impacted.
And finally, native gems using APIs such a `pthread_atfork(3)` won't be impacted either, as the native thread will remain the same in the child.

Use a fiber rather than a thread to implement `clean_fork`

---

CHANGELOG.md
lib/pitchfork.rb
lib/pitchfork/http_server.rb

Fix: https://github.com/Shopify/pitchfork/pull/49#issuecomment-1587264229
The fiber solution has the huge drawback on restricting the stack space to just 4kiB, which is way too small for sizeable applications.
Instead we can use a throw with a callable argument to unwind the stack and resume execution.

Use throw/catch to unwind the stack post fork

---

lib/pitchfork/chunked.rb

`Rack::VERSION` is deprecated.

Avoid Rack 3.x deprecation warnings

---

ext/pitchfork_http/pitchfork_http.c
test/integration/test_parser_error.rb

```bash
curl -i 'http://localhost:8080/' -H 'cookie: utf8=™;
HTTP/1.1 400 Bad Request
```
After tracking this down, it was caused by the ragel version used. After upgrading it the problem is solved.

Fix handling on non-ASCII headers

---

CHANGELOG.md
lib/pitchfork/http_server.rb
lib/pitchfork/info.rb
test/integration/fork_unsafe.ru
test/integration/test_reforking.rb

When some part of an application is hard or impossible to make fork-safe, but rarely called, it's possible to simply mark the worker as fork unsafe, and rely on its siblings to fork the next generation.
In the eventually where all the workers end up marked fork unsafe, no new generation will be spawned, unless of course one of the unsafe workers die and is replaced by a fresh one.
So this is only meant as a workaround for infrequently called things.

Allow to mark workers as fork unsafe

---

docs/CONFIGURATION.md
lib/pitchfork/configurator.rb
lib/pitchfork/http_server.rb
test/integration/test_configuration.rb

This is useful for reporting if the hook is used to terminate the worker or something.
E.g. if you detect something went wrong and the worker must exit, you may want to report some informations about the request that caused it.

Pass the last request env to after_request_complete

---

.devcontainer/devcontainer.json
Dockerfile

This project already have a Dockerfile to make it easier to develop since it depends on a lot of feature from linux. However, if users develop using VSCode it would be good to have a devcontainer config to make this Dockerfile just work.
This require changing the base image to the devcontainer images that include the vscode server and other developer tools.

Add devcontainer configuration

---

CHANGELOG.md
docs/CONFIGURATION.md
lib/pitchfork/configurator.rb
lib/pitchfork/http_server.rb

Can be used to start an instrumentation thread or similar.
FYI @DazWorrall

Add an `after_monitor_ready` callback

---

CHANGELOG.md
docs/CONFIGURATION.md
lib/pitchfork/configurator.rb
lib/pitchfork/http_server.rb
test/integration/test_boot.rb

Some low level fork safety bugs can cause workers to lock up before they reach the process client loop.
See: https://github.com/Shopify/pitchfork/pull/67
While such bugs should be avoided, Pitchfork should still try to recover from it, and killing newly spawned workers that didn't reach ready state should prevent cascading failure.

Implement `spawn_timeout` configuration

---

lib/pitchfork/children.rb
lib/pitchfork/http_server.rb
lib/pitchfork/worker.rb

Makes it easier to monkey patch it for debug purposes.

Refactor the hard timeout codepaths

---

bin/dev-console
lib/pitchfork.rb
lib/pitchfork/children.rb
lib/pitchfork/http_server.rb
test/integration/test_boot.rb
test/integration/test_reforking.rb
test/integration_test_helper.rb
test/unit/test_children.rb

Ref: https://github.com/Shopify/pitchfork/issues/79
It can happen that the new mold was forked while at an unsafe point, causing the middle process to crash.
When we detect this happens, we should abandon this mold.
Currently abandoning the mold cause a graceful shutdown, in the future we could try creating a new mold to replace it.

Handle fork_sibling failing repeatedly

---

lib/pitchfork/http_server.rb

which is helpful for logging for example worker.nr in app error handling. we're in the process of tracking down a SSL session corruption bug in our HTTP library and we're trying to work out when it occurs if its happening across all workers or just one, it's impossible to tell at the moment because the hostname for all the errors is the same, being about to log `worker.nr` alongside that would answer the question

expose pitchfork worker in env

---

lib/pitchfork/http_server.rb

Ensure we won't hammer the process with similar signals.
Normally it doesn't happen as we sleep for 1 second, but monitor loop may be woken-up for other reasons which can lead to thousands of KILL signals being sent to to the same child.
One every 1 second should be plenty.

Extend child deadline after sending a hard timeout

---

lib/pitchfork/http_server.rb

`START_CTX[:cwd]` is already completly unused.
Like the comment states, we can get rid of it. It was used in conjunction with USR2 to modify a running master into spawning workers with different arguments (for a rolling deploy with only one host for example) which is a non-goal for Pitchfork and does in fact not work anymore anyways.
Slight behaviour change: argv was modified to contain the default listener if none was specified which made it appear in the proctitle. This was probably done for other reasons, and I don't see a particular reason why it should continue to do so.

Remove `START_CTX`

---

docs/CONFIGURATION.md

I've read https://github.com/Shopify/pitchfork/issues/87, compaction in particular was called out however the current example already does this as well so I believe this is fine without elaborating on that.

Promote `Process.warmup` for `after_mold_fork` with supported Rubies

---

lib/pitchfork/children.rb
lib/pitchfork/worker.rb

This used to be at least occasionally updated in https://github.com/Shopify/pitchfork/commit/aebdc2ec682df37705db6320f1f4a8d5f7f5daf6, in https://github.com/Shopify/pitchfork/commit/7239fba1036e88d0e7dedddbe1cfafc1e2030cad it got removed
The user is required to call refresh themselves in order to not get stale results after first access.
Removing `MemInfo` may be a overkill? You probably use that at Shopify, I distinctly remember a graph about cow efficiency somewhere. Generally I'm unsure about the level of backwards compatibility you want to guarantee at this time.

Remove stale mem_info function

---

exe/pitchfork

>   -c, --config-file FILE   Unicorn-specific config file
>   -c, --config-file FILE   Pitchfork-specific config file
> pitchfork v6.1.0
> pitchfork v0.13.0

Fix `--help` and `--version` reporting unicorn values

---

docs/CONFIGURATION.md
examples/pitchfork.conf.service.rb
lib/pitchfork/children.rb
lib/pitchfork/configurator.rb
lib/pitchfork/http_server.rb
lib/pitchfork/message.rb
lib/pitchfork/shared_memory.rb
lib/pitchfork/worker.rb
test/integration/test_service_worker.rb

Ref: https://github.com/Shopify/pitchfork/issues/110
It's not uncommon for applications to want to have some background threads doing regular work for various purposes (e.g. emitting metrics, prewarming node local caches, etc).
Currently the best way to do it, is to spawn some background threads in the `after_mold_fork`, but this isn't great as the mold may fork at any moment to spawn a new worker, and forking while background threads may be doing work is risky.
Instead we can provide a dedicated service worker process to run these threads.

Implement service workers

---

lib/pitchfork/http_server.rb

The returned object is an IO subclass, and shouldn't be closed by `close_all_ios!`.

Mark Waiter.prep_readers return value as safe to keep

---

CHANGELOG.md
Gemfile.lock
ext/pitchfork_http/extconf.rb
ext/pitchfork_http/memory_page.c
ext/pitchfork_http/pitchfork_http.c
ext/pitchfork_http/pitchfork_http.rl
lib/pitchfork.rb
lib/pitchfork/http_server.rb
lib/pitchfork/shared_memory.rb
pitchfork.gemspec
test/test_helper.rb
test/unit/test_worker.rb

We're only using a small part of it, so it's much better to inline that functionality.
Raindrops is licensed under LGPL v2.1+, and Pitchfork under GPL 2+.
According to [https://www.gnu.org/licenses/gpl-faq.](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) it's authorized to redistribute it under GPL.

Eliminate dependency on Raindrops

---

test/unit/test_http_parser.rb

`URI::REGEXP` is gone but the same value is accessible as `URI::RFC2396_REGEXP`.

Fix test_http_parser with ruby-head

---

CHANGELOG.md
lib/pitchfork/http_server.rb

This skips `at_exit` and finalizer hooks, which shouldn't be needed.
There is little point wasting time running all of these, all these hooks will be ran when both the parent and the child exit, I can see no use case for wasting time and risking deadlock here.

Use `exit!` for exiting the middle process when forking a new worker or mold.

---

.github/workflows/ci.yml

#148 fails but it's not the code's fault, GitHub switched to Ubuntu 24.04 for `ubuntu-latest`. This just restores the way it was while we fix #149.

Use Ubuntu 22.04 for now

---

README.md

I tried to fix up minor details that I found which seemed like they could be improved.  If you would like me to explain any suggestions, please ask as many questions as you'd like.  If you think I misunderstood the text I was trying to improve, please let me know and I can try again.

punctuation proof-reading & grammar glow-up

---

CHANGELOG.md
docs/CONFIGURATION.md
lib/pitchfork/configurator.rb
lib/pitchfork/http_server.rb

- Add documentation for the `before_worker_exit` hook (added in 0efdfcff2e398277a69987b9ab2c75ed395ac6c4).
- Remove accessor for `after_load` (removed in 9f3020ab9dd61751ad41b49f0fc3dfa85b0f277b). May cause NoMethodError, so mentioned in the changelog.
- Update code comment mentioning `after_fork` (split in 596a458a6ba2c3ae9a82fb75e0e871853d08b636).

Updates after added/removed/split callbacks

---

docs/CONFIGURATION.md
lib/pitchfork/configurator.rb
lib/pitchfork/http_server.rb
lib/pitchfork/refork_condition.rb
lib/pitchfork/worker.rb
test/integration/test_boot.rb
test/integration/test_info.rb
test/integration/test_reforking.rb

Consistently log worker `nr` (where relevant) first, then `generation`, then `pid`. Use lowercase letters in most such messages.
Fixes #153

Consistent logging

---

docs/DESIGN.md
docs/PHILOSOPHY.md
docs/REFORKING.md
docs/SIGNALS.md
docs/TUNING.md
examples/nginx.conf
examples/pitchfork.conf.rb
ext/pitchfork_http/c_util.h
ext/pitchfork_http/epollexclusive.h
lib/pitchfork/children.rb
lib/pitchfork/http_server.rb
lib/pitchfork/info.rb
lib/pitchfork/worker.rb
test/integration/README
test/integration/test_heartbeat_timeout.rb
test/slow/test_signals.rb
test/test_helper.rb

While reading https://byroot.github.io/ruby/performance/2025/03/04/the-pitchfork-story.html, I noticed this sentence:
> Now that I could more significantly change the server, I decided to move the responsibility of spawning new workers out of the master process, which I renamed “monitor process” for the occasion.
I had always been a bit confused by the code and documents using both “master” and “monitor” terms, and honestly thought they meant two different things.
Now, in this PR, the first commit changes docs and comments to always use “monitor”.
The 2nd commit changes (almost) all mentions of “Unicorn” into “Pitchfork” – but of course not when mentioning Pitchfork’s history, etc.
~There’s still some mentions of “master”, e.g. `HttpServer#master_sleep`, `HttpServer#awaken_master`, …

Change some words: master→monitor and unicorn→pitchfork

---

docs/CONFIGURATION.md
lib/pitchfork/configurator.rb
lib/pitchfork/http_server.rb
test/integration/test_configuration.rb
test/integration/test_reforking.rb

While I think `10%` is a good default, this may be too much or too little depending on the number of worker processes and how longthe `after_worker_fork` callbacks takes.

Make the rollout cadence configurable

---

CHANGELOG.md
lib/pitchfork/http_server.rb
test/integration/test_reforking.rb

If we reset the handlers in the current process we are likely to get a second signal and bypass the exit hooks.
Fix: https://github.com/Shopify/pitchfork/issues/168

Fix `before_worker_exit`

---

lib/pitchfork.rb
test/integration/frozen_string.ru
test/integration/test_rack_pragmas.rb

Resolves https://github.com/Shopify/pitchfork/issues/173
Prior to these changes, Ruby pragmas (including `frozen-string-literal`) were inserted in the wrong place.
This might be a breaking change.

Ensure Rack config pragmas are kept during application building
